name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pyarrow=2.0
  - pip:
      - wandb==0.12.21
      - jupyterlab==3.4.4
      - pandas-profiling==2.11.0